### ISSUE TITLE
generated quick_search_config.yml is empty

### ISSUE THREAD

**Issue by jronallo** [NCSU-Libraries/quick_search#5]
Just tried using the latest master and after running the generator I can a config/quick_search_config.yml file but it is empty.

**Comment by kbeswick** [comment]
That is odd. I just tested a fresh install of master and it worked as expected. I also a tested a fresh install of the branch in #3  and also works as expected.

**Comment by jronallo** [comment]
Yes, this was some strangeness on my end. Reran and config file had data.
