### ISSUE TITLE
don't include actual URLs in placeholder searcher results

### ISSUE THREAD

**Issue by jronallo** [NCSU-Libraries/quick_search#8]
Either remove non-example URLs or have them point to the project or the NCSU Libraries. No knowing what might be placed up at a couple of those URLs at some point. Right now it looks like advertising for web hosting or something.

**Comment by kbeswick** [comment]
fixed: https://github.com/NCSU-Libraries/quick_search-placeholder_searcher/commit/1e0b89126c6162a5bac7b1512cc31f594c89e1a5
